# Criando um Mapas interativo de regiões e renda do DF

Nesse projeto eu queria criar um dataset interativo e acessorasse as pessoas a ter melhores informações de indiciadores socioeconomícos de suas RAs no DF, farei o projeto o melhor possível dentro das minhas possibildiades, mas ressalto que o principal problema é encontrar informações confiáveis e auditáveis para tal projeto.

As informações que peguei foram disponibilizadas pelo Instituto de Pesquisas Estatísticas do Distrito Federa (IPE-DF), mas realizar uma busca nesse site é uma bomba e ta tudo desorganizado.

In [39]:
# Vamos começar importanto as bibliotecas, em especial geopandas e folium para dados geográficos
import pandas as pd
import geopandas as gpd
import folium

In [40]:
gdf = gpd.read_file("Limite_RA_2025.json") # geoJson com os poligonos de cada RA
dados = pd.read_excel("DataSet.xlsx", skiprows=2) # dados sociais, eu ainda tenho o Indice de Gini aqui

renda = pd.read_csv("09-renda_ra_pdad_2024_identificadoRA.csv")
domicilios = pd.read_csv("05-composicao_domicilios_identificadoRA.csv")
infraestrutura = pd.read_csv("07-infraestrutura_urbana_identificadoRA.csv")
mobilidade = pd.read_csv("08-mobilidade_trabalho_identificadoRA.csv")

In [41]:
print(gdf.columns)
print(dados.columns)
#print(pd.read_excel("DataSet.xlsx", header=None).head(10))

Index(['id', 'fid', 'ra_cira', 'ra_codigo', 'ra_nome', 'ra_path', 'ra_areakm2',
       'st_area_sh', 'st_length_', 'geometry'],
      dtype='object')
Index(['NÚMEROS DAS RAs', 'DESCRIÇÃO', 'Valores Absolutos (RS 1,00)',
       'Valores em salários mínimos ', 'índice de Gini', 'Unnamed: 5',
       'numero_filhos'],
      dtype='object')

In [42]:
# Renomear colunas para algo simples
dados = dados.rename(columns={
    "DESCRIÇÃO": "ra",
    "Valores Absolutos (RS 1,00)": "renda",
    "índice de Gini": "gini"
})

print(dados.head(10))

  NÚMEROS DAS RAs                  ra         renda  \
0            RA-I        Plano Piloto  16815.024597
1           RA-II                Gama   3622.426392
2          RA-III          Taguatinga   4427.833037
3           RA-IV          Brazlândia   2818.001647
4           RA-IX           Ceilândia    3235.81864
5            RA-V          Sobradinho    6753.75393
6           RA-VI          Planaltina   1865.646922
7          RA-VII             Paranoá   1941.689217
8         RA-VIII  Núcleo Bandeirante   4759.750571
9            RA-X               Guará   7420.551532

  Valores em salários mínimos       gini  Unnamed: 5  numero_filhos
0                    11.908658  0.470965         NaN            NaN
1                     2.565458  0.476452         NaN            NaN
2                     3.135859  0.472634         NaN            NaN
3                     1.995752  0.387869         NaN            NaN
4                     2.291656  0.433131         NaN            NaN
5                     4.783112  0.515685         NaN            NaN
6                      1.32128  0.432003         NaN            NaN
7                     1.375134  0.309170         NaN            NaN
8                     3.370928  0.466706         NaN            NaN
9                     5.255348  0.523741         NaN            NaN

In [43]:
# Manter o que interessa
dados = dados[["ra","renda","gini","numero_filhos"]]
dados["renda"] = pd.to_numeric(dados["renda"], errors="coerce")
print(dados.dtypes)

ra                object
renda            float64
gini             float64
numero_filhos    float64
dtype: object

In [44]:
dados["renda"] = dados["renda"].fillna(dados["renda"].mean()) # Trata os NaN
#dados = dados.dropna()
print(dados.head(10))

                   ra         renda      gini  numero_filhos
0        Plano Piloto  16815.024597  0.470965            NaN
1                Gama   3622.426392  0.476452            NaN
2          Taguatinga   4427.833037  0.472634            NaN
3          Brazlândia   2818.001647  0.387869            NaN
4           Ceilândia   3235.818640  0.433131            NaN
5          Sobradinho   6753.753930  0.515685            NaN
6          Planaltina   1865.646922  0.432003            NaN
7             Paranoá   1941.689217  0.309170            NaN
8  Núcleo Bandeirante   4759.750571  0.466706            NaN
9               Guará   7420.551532  0.523741            NaN

In [45]:
# Conferindo se o GeoJSON tem a coluna 'ra'
#print(gdf[["ra_cira","ra_codigo", "ra_nome"]].head(40))
display(gdf[["ra_cira","ra_codigo", "ra_nome"]].head(40))

    ra_cira  ra_codigo                    ra_nome
0         9      RA-IX                  CEILÂNDIA
1        32   RA-XXXII  SOL NASCENTE E POR DO SOL
2        29    RA-XXIX                        SIA
3        19     RA-XIX             CANDANGOLÂNDIA
4        21     RA-XXI            RIACHO FUNDO II
5        24    RA-XXIV                   PARK WAY
6        16     RA-XVI                   LAGO SUL
7        18   RA-XVIII                 LAGO NORTE
8        34   RA-XXXIV                  ARAPOANGA
9         8    RA-VIII         NÚCLEO BANDEIRANTE
10       20      RA-XX               ÁGUAS CLARAS
11       22    RA-XXII         SUDOESTE/OCTOGONAL
12        1       RA-I               PLANO PILOTO
13        5       RA-V                 SOBRADINHO
14       10       RA-X                      GUARÁ
15       11      RA-XI                   CRUZEIRO
16       17    RA-XVII               RIACHO FUNDO
17        3     RA-III                 TAGUATINGA
18       23   RA-XXIII                     VARJÃO
19       25     RA-XXV                       SCIA
20       30     RA-XXX              VICENTE PIRES
21       33  RA-XXXIII                 ARNIQUEIRA
22        6      RA-VI                 PLANALTINA
23       28  RA-XXVIII                     ITAPOÃ
24       15      RA-XV           RECANTO DAS EMAS
25       12     RA-XII                  SAMAMBAIA
26       13    RA-XIII                SANTA MARIA
27       14     RA-XIV              SÃO SEBASTIÃO
28       26    RA-XXVI              SOBRADINHO II
29       35    RA-XXXV                AGUA QUENTE
30        4      RA-IV                 BRAZLÂNDIA
31       31    RA-XXXI                     FERCAL
32        2      RA-II                       GAMA
33       27   RA-XXVII            JARDIM BOTÂNICO
34        7     RA-VII                    PARANOÁ

# Agora vamos ao merge

Agora que temos uma ideia de como são os dados vamos ao merge.

Antes uma verificação.

In [50]:
datasets = {
    "GeoJSON": gdf,
    "Renda": renda,
    "Domicílios": domicilios,
    "Infraestrutura": infraestrutura,
    "Mobilidade": mobilidade
}

for nome, df in datasets.items():
    print(f"\n--- {nome} ---")
    print("Linhas:", len(df))
    print("RAs identificadas:", df["ra_cira"].nunique())
    print("Sem ra_cira:", df["ra_cira"].isna().sum())

--- GeoJSON ---
Linhas: 35
RAs identificadas: 35
Sem ra_cira: 0

--- Renda ---
Linhas: 36
RAs identificadas: 35
Sem ra_cira: 1

--- Domicílios ---
Linhas: 36
RAs identificadas: 35
Sem ra_cira: 1

--- Infraestrutura ---
Linhas: 36
RAs identificadas: 35
Sem ra_cira: 1

--- Mobilidade ---
Linhas: 36
RAs identificadas: 35
Sem ra_cira: 1

De fato tem um sem identificação, porque no dataset original havia "Área rural" que não é uma RA

In [51]:
renda_rural = renda[renda["ra_cira"].isna()]
domicilios_rural = domicilios[domicilios["ra_cira"].isna()]
infraestrutura_rural = infraestrutura[infraestrutura["ra_cira"].isna()]
mobilidade_rural = mobilidade[mobilidade["ra_cira"].isna()]

In [52]:
renda_merge = renda.drop(columns=["RA"])
domicilios_merge = domicilios.drop(columns=["RA"])
infraestrutura_merge = infraestrutura.drop(columns=["RA"])
mobilidade_merge = mobilidade.drop(columns=["RA"])

In [53]:
gdf_final = (
    gdf
    .merge(renda, on="ra_cira", how="left")
    .merge(domicilios, on="ra_cira", how="left", suffixes=("", "_dom"))
    .merge(infraestrutura, on="ra_cira", how="left", suffixes=("", "_infra"))
    .merge(mobilidade, on="ra_cira", how="left", suffixes=("", "_mob"))
)

In [54]:
display(gdf_final.head(5))
display(gdf_final.columns)
display("Dimensões (lina, colunas)",gdf_final.shape)

,id,fid,ra_cira,ra_codigo,ra_nome,ra_path,ra_areakm2,st_area_sh,st_length_,geometry,...,pct_trabalho_presencial,pct_trabalho_remoto,pct_trabalho_hibrido,principal_destino_trabalho,pct_principal_destino,pct_trabalha_na_propria_ra,faixa_mediana_deslocamento,pct_deslocamento_ate_30min,pct_deslocamento_acima_1h,transporte_principal
0,regioes_administrativas.1,1,9,RA-IX,CEILÂNDIA,https://www.geoservicos.ide.df.gov.br/anexos/m...,192.656942,1.926569e+08,117499.507567,"MULTIPOLYGON (((149858.575 8238122.607, 149856...",...,87.805602,6.964259,5.230138,Ceilândia,40.766943,40.766943,Acima de 30 minutos até 45 minutos,49.826547,22.107619,Ônibus
1,regioes_administrativas.2,2,32,RA-XXXII,SOL NASCENTE E POR DO SOL,https://www.geoservicos.ide.df.gov.br/anexos/m...,40.491664,4.049166e+07,37498.813107,"MULTIPOLYGON (((161030.452 8251189.866, 161532...",...,96.173860,2.978522,0.847618,Ceilândia,25.443813,14.808337,Acima de 15 minutos até 30 minutos,51.821878,14.922942,Ônibus
2,regioes_administrativas.3,3,29,RA-XXIX,SIA,https://www.geoservicos.ide.df.gov.br/anexos/m...,29.050896,2.905090e+07,31328.941199,"MULTIPOLYGON (((187388.403 8257642.711, 186391...",...,86.609413,11.707652,1.682935,SIA,41.761274,41.761274,Acima de 15 minutos até 30 minutos,87.458724,5.602951,Automóvel
3,regioes_administrativas.4,4,19,RA-XIX,CANDANGOLÂNDIA,https://www.geoservicos.ide.df.gov.br/anexos/m...,6.601864,6.601864e+06,11012.005644,"MULTIPOLYGON (((185918.037 8245317.554, 185912...",...,90.874867,4.770230,4.354903,Plano Piloto,42.693565,30.960246,Acima de 15 minutos até 30 minutos,67.047719,9.051839,Automóvel
4,regioes_administrativas.5,5,21,RA-XXI,RIACHO FUNDO II,https://www.geoservicos.ide.df.gov.br/anexos/m...,38.467155,3.846716e+07,29818.864175,"MULTIPOLYGON (((174586.609 8242596.511, 174580...",...,91.155142,3.740995,5.103863,Plano Piloto,29.605022,20.022502,Acima de 30 minutos até 45 minutos,42.518293,22.231787,Ônibus

Index(['id', 'fid', 'ra_cira', 'ra_codigo', 'ra_nome', 'ra_path', 'ra_areakm2',
       'st_area_sh', 'st_length_', 'geometry', 'RA', 'renda_média', 'P10',
       'P25/Q1', 'P50/mediana', 'P75/Q3', 'P90', 'RA_dom', 'media_moradores',
       'mediana_moradores', 'pct_domicilios_com_criancas',
       'media_criancas_domicilios_com_criancas', 'pct_unipessoal',
       'pct_monoparental_feminino', 'pct_casal_com_filhos',
       'pct_casal_sem_filhos', 'pct_outros_arranjos', 'pct_condominio_fechado',
       'pct_paga_taxa_condominial', 'mediana_taxa_condominial', 'RA_infra',
       'pct_rua_pavimentada', 'pct_calcada', 'pct_calcadas_com_rampa',
       'pct_iluminacao', 'pct_drenagem', 'pct_arborizacao', 'pct_parque_praca',
       'pct_ciclovia', 'pct_travessia_sinalizada', 'pct_ponto_onibus',
       'pct_policiamento', 'pct_lixo_entulho', 'pct_esgoto_ceu_aberto',
       'pct_alagamento', 'RA_mob', 'pct_trabalho_presencial',
       'pct_trabalho_remoto', 'pct_trabalho_hibrido',
       'principal_destino_trabalho', 'pct_principal_destino',
       'pct_trabalha_na_propria_ra', 'faixa_mediana_deslocamento',
       'pct_deslocamento_ate_30min', 'pct_deslocamento_acima_1h',
       'transporte_principal'],
      dtype='object')

'Dimensões (lina, colunas)'

(35, 56)

In [ ]:
display(gdf_final[["RA_dom","RA_infra"]]

Essa etapa aqui cria o mapa de fato

In [17]:
# Criando o mapa

mapa = folium.Map(location=[-15.78,-47.93], zoom_start=10)

folium.Choropleth(
    geo_data=gdf,
    data=gdf,
    columns=["ra","renda"],
    key_on="feature.properties.ra",
    fill_color="RdYlBu",
    legend_name="Renda média"
).add_to(mapa)

# Adiciona os dados num tooltip
folium.GeoJson(
    gdf,
    tooltip=folium.GeoJsonTooltip(
        fields=["ra", "renda", "gini"],
        aliases=["Região:", "Renda média:", "Índice de Gini:"],
        localize=True
    )
).add_to(mapa)

In [18]:
mapa.save("mapa_renda_df.html")

AssertionError: The field ra is not available in the data. Choose from: ().